ci:
  skip:
  - terraform-fmt
  - terraform-validate
  - infra-visualize
  - diagrams-visualize

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://gitlab.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ["--max-line-length", "88", "--extend-ignore", "E203,E501"]
  - repo: local
    hooks:
      - id: infra-visualize
        name: Visualize Infra
        language: system
        entry: task -t infra/Taskfile.yml visualize
        pass_filenames: false
      - id: diagrams-visualize
        name: Visualize Diagrams
        language: system
        entry: task -t diagrams/Taskfile.yml
        pass_filenames: false
