version: "3"

vars:
  PROJECT: k3d-data-platform
  TAG: '{{default "latest" .TAG}}'
  DOCKERFILE: '{{default "." .DOCKERFILE}}'

tasks:
  docker:build:
    cmds:
      - DOCKER_SCAN_SUGGEST=false docker build --tag {{.PROJECT}}-{{.SERVICE}}:{{.TAG}} {{.DOCKERFILE}}

  docker:tag:
    cmds:
      - docker tag {{.PROJECT}}-{{.SERVICE}}:{{.TAG}} localhost:5001/{{.PROJECT}}-{{.SERVICE}}:{{.TAG}}

  docker:push:
    cmds:
      - docker push localhost:5001/{{.PROJECT}}-{{.SERVICE}}:{{.TAG}}
