version: "3"

vars:
  PROJECT: kind-data-platform
  IMAGE: "{{.PROJECT}}-{{.SERVICE}}"
  TAG: '{{default "latest" .TAG}}'

tasks:
  docker:build:
    cmds:
      - DOCKER_SCAN_SUGGEST=false docker build --tag {{.IMAGE}}:{{.TAG}} . --platform arm64

  kind:load:
    cmds:
      - kind load docker-image {{.IMAGE}}:{{.TAG}} --name {{.PROJECT}}

  terraform:apply:
    cmds:
      - terraform init
      - terraform apply --target kind_cluster.default
      - terraform apply
