version: "3"

includes:
  base: ../Taskfile.yml

tasks:
  setup:
    cmds:
      - terraform init
      - terraform apply --target kind_cluster.default -auto-approve
      - task: base:docker:build
        vars:
          SERVICE: airflow
          DOCKERFILE: ../airflow
      - task: base:kind:load
        vars:
          SERVICE: airflow
      - terraform apply -auto-approve

  expose:localstack:
    cmds:
      - kubectl port-forward svc/localstack 4566:4566 --namespace localstack

  setup:localstack-services:
    cmds:
      - terraform -chdir=localstack-services init
      - terraform -chdir=localstack-services apply -auto-approve

  teardown:localstack-services:
    cmds:
      - terraform -chdir=localstack-services destroy -auto-approve

  teardown:
    cmds:
      - kind delete cluster --name {{.PROJECT}}
      - rm -f {{.PROJECT}}-config terraform.tfstate terraform.tfstate.backup

  visualize:
    cmds:
      - terraform graph | docker run --rm -i nshine/dot dot -Tsvg > graph.svg

  visualize:localstack-services:
    cmds:
      - terraform -chdir=localstack-services graph | docker run --rm -i nshine/dot dot -Tsvg > localstack-services/graph.svg
