version: "3"

includes:
  base: ../Taskfile.yml

vars:
  SERVICE: airflow
  SERVICE_REPOSITORY: apache-airflow/airflow

tasks:
  default:
    cmds:
      - task: base:docker:build
      - task: base:kind:load
      - helm upgrade {{.SERVICE}} {{.SERVICE_REPOSITORY}} --namespace {{.SERVICE}} --set images.airflow.repository={{.IMAGE}} --set images.airflow.tag={{.TAG}}
