version: "3"

includes:
  base: ../Taskfile.yml

vars:
  SERVICE: airflow

tasks:
  default:
    cmds:
      - task: base:docker:build
      - task: base:docker:tag
      - task: base:docker:push
      - terraform -chdir=../infra apply -replace="helm_release.airflow"
