name: "Docker"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker:
    name: "Docker"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Hadolint Airflow
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: ./airflow/Dockerfile

      - name: Run Hadolint Dbt
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: ./dbt/Dockerfile
