name: "Terraform"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init infra
        id: init-infra
        working-directory: ./infra
        run: terraform init

      - name: Terraform Validate infra
        id: validate-infra
        working-directory: ./infra
        run: terraform validate -no-color

      - name: Terraform Init localstack-resources
        id: init-localstack-resources
        working-directory: ./infra/localstack-resources
        run: terraform init

      - name: Terraform Validate localstack-resources
        id: validate-localstack-resources
        working-directory: ./infra/localstack-resources
        run: terraform validate -no-color
